[package]
name = "cs_epic_config"
version = "1.0.0" # 1.0.0 = 3.6.0
authors = ["Epic Foundation <info@epiccash.com>", "Likho", "sneurlax"]
description = "Configuration for epic, a simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/cypherstack/epic"
workspace = ".."
edition = "2021"

[dependencies]
rand = "0.6"
serde = "1"
serde_derive = "1"
toml = "0.4"
dirs = "1.0.3"

epic_core = { package = "cs_epic_core", path = "../core", version = "^1.0.1" }
epic_servers = { package = "cs_epic_servers", path = "../servers", version = "^1.0.0" }
epic_p2p = { package = "cs_epic_p2p", path = "../p2p", version = "^1.0.2" }
epic_util = { package = "cs_epic_util", path = "../util", version = "^1.0.1" }

[dev-dependencies]
pretty_assertions = "0.5.1"
